const site = 'https://www.codeflowstudios.be';
// Reviewed against app/**/page.tsx and public/**/index.html. These destinations
// retain their existing access rules; only this directory is admin-only.
export const routes = [
  ['Marketing dashboard', '/dashboard/'], ['Onboarding', '/onboarding/'],
  ['Marketing', '/services/marketing/'], ['Graphic design', '/services/graphic-design/'],
  ['Software development', '/services/software-development/'], ['Rebranding', '/services/rebranding/'],
  ['Skumic showcase', '/skumic/'], ['Skumic game', '/skumic-game/', true],
  ['Beatdown City', '/beatdown-city/'], ['Beatdown City 0.14', '/beatdown-city-014/'],
  ['Flow Community', '/flow-community/'], ['Nightly Build Club (doorverwijzing)', '/nightly-build-club/'],
  ['Flow Shop', '/shop/'], ['Juridisch', '/legal/'],
  ['ATN contactkaart', '/atn/ATN-contact.vcf'],
];
const railway = 'https://railway.com/project/';
export const projects = [
  ['Website / Skumic', 'c33f4f01-7f6e-4977-91bb-c7b0d747a6ef', 'f736fbd3-12ac-43ab-89ef-d2b49d0b0ff0'],
  ['What’s Next', '90407548-ac90-46c1-b4cc-11717feb94e0', 'b13456a3-f19f-4219-b225-292910ae3bc6'],
  ['Marketing AI', 'cbba547e-3a09-4e5b-8dfb-b4bc4d108054', 'd255d01b-a45d-4cdd-83a3-e3bff284db51'],
  ['Codeflow Studios Production (leeg project)', 'dd5714a0-1270-49fa-8229-cc587de44736'],
];
export const escapeHtml = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = (name, url) => `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(name)} <span aria-hidden="true">↗</span></a>`;
export const css = `:root{color-scheme:dark;font-family:Arial,Helvetica,sans-serif;background:#121214;color:#f6f6f8}*{box-sizing:border-box}body{margin:0;line-height:1.6}main{max-width:1160px;margin:auto;padding:40px 24px 70px}header{display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid #36363d;padding-bottom:24px}.brand{font-size:.8rem;letter-spacing:.14em;font-weight:700;color:#ff854d}h1{font-size:clamp(2.4rem,6vw,4rem);line-height:1.05;letter-spacing:-.05em;margin:24px 0 16px}h2{font-size:1.35rem;margin:0 0 16px}p{color:#b9b9c2}a{color:inherit;text-decoration:none}a:hover{color:#ff854d}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:30px}section{min-width:0;background:#1b1b1e;border:1px solid #36363d;border-radius:12px;padding:28px}.wide{grid-column:1/-1}.links{display:grid;gap:9px}.links a{display:flex;justify-content:space-between;gap:16px;padding:13px 0;border-bottom:1px solid #36363d;overflow-wrap:anywhere}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.stats strong{font-size:2rem;display:block}.stats span,.muted{color:#b9b9c2;font-size:.9rem}.badge{display:inline-block;border:1px solid #65523b;border-radius:30px;padding:4px 12px;color:#ffc393;font-size:.8rem}button,.button{display:inline-block;border:0;border-radius:6px;background:#ff854d;color:#151214;padding:12px 20px;min-height:46px;font:700 .95rem Arial;cursor:pointer}input{width:100%;padding:13px;border:1px solid #686871;border-radius:6px;background:#121214;color:#fff;font:inherit}label{display:block;margin:20px 0 7px}a:focus-visible,button:focus-visible,input:focus-visible{outline:2px solid #ff854d;outline-offset:4px}.login{max-width:490px;padding-top:10vh}.login section{margin-top:30px}.login button{width:100%;margin-top:24px}.error{color:#ffadb9}footer{margin-top:32px;color:#9999a4;font-size:.85rem}@media(max-width:650px){main{padding:24px 16px 45px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}section{padding:22px}.stats{gap:8px}.stats span{font-size:.8rem}header{align-items:flex-start}.login{padding-top:30px}}`;
export function page(body) {
  return `<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Admin · Codeflow Studios</title><link rel="stylesheet" href="/admin/style.css"></head><body>${body}</body></html>`;
}
export function loginPage(token, error = '') {
  return page(`<main class="login"><div class="brand">CODEFLOW STUDIOS / ADMIN</div><h1>Welkom terug.</h1><p>Log in om je werkplek te openen.</p><section>${error ? `<p class="error" role="alert">${escapeHtml(error)}</p>` : ''}<form method="post" action="/admin/login"><input type="hidden" name="csrf" value="${escapeHtml(token)}"><label for="username">Gebruikersnaam</label><input id="username" name="username" autocomplete="username" required maxlength="128"><label for="password">Wachtwoord</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="512"><button>Inloggen</button></form></section></main>`);
}
export function dashboard(csrf) {
  return page(`<main><header><div class="brand">CODEFLOW STUDIOS / ADMIN</div><form method="post" action="/admin/logout"><input type="hidden" name="csrf" value="${escapeHtml(csrf)}"><button>Uitloggen</button></form></header><h1>Alles op één plek.</h1><p>Je website, mail en projecten binnen handbereik.</p><div class="grid"><section class="wide"><h2>Website analytics</h2><span class="badge">Nog niet gekoppeld</span><div class="stats"><div><strong>—</strong><span>Bezoekers</span></div><div><strong>—</strong><span>Pageviews</span></div><div><strong>—</strong><span>Referrers</span></div></div><p>Er is nog geen bezoekersanalytics aangesloten. Deze streepjes betekenen dat er geen gegevens beschikbaar zijn.</p><p class="muted">Volgende stap: kies een analyticsbron, plaats de benodigde tracking op de publieke website en verbind de rapportage via een server-side API. API-sleutels blijven in Railway secrets.</p></section><section><h2>Webmail</h2><p>codeflowstudios@proton.me</p><div class="links">${link('Codeflow webmail', `${site}/webmail`)}${link('Proton Mail', 'https://mail.proton.me/')}</div></section><section><h2>Productivity</h2><span class="badge">What’s Next · productie</span><p>Start met je volgende kleine stap, focus en wissel tussen projecten.</p><div class="links">${link('Open What’s Next', 'https://whats-next-web-production.up.railway.app/')}</div></section><section class="wide"><h2>Website & interne links</h2><p class="muted">Routeoverzicht uit de website-repository. De bestemmingen behouden hun eigen toegangsrechten.</p><div class="links">${routes.map(([name, route, runtime]) => link(name, `${runtime ? 'https://codeflow-studios-production.up.railway.app' : site}${route}`)).join('')}</div></section><section><h2>Railway</h2><div class="links">${projects.map(([name,id,service]) => link(name, `${railway}${id}${service ? `/service/${service}` : ''}`)).join('')}</div></section><section><h2>GitHub</h2><div class="links">${['Codeflow-Studios/Codeflow-Website','Codeflow-Studios/MarketingAI','GillianMarechal/WhatsNext'].map(repo => link(repo, `https://github.com/${repo}`)).join('')}</div></section></div><footer>Privéomgeving · Sessie verloopt na 8 uur.</footer></main>`);
}
