'use client';
import { useRef,useState } from 'react';
import { Gamepad2,Play,Maximize,Square,RotateCcw } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import type { Language } from './shared';

// The supplied Codeflow Tower 0.2 archive contains a Windows Godot 4 C# build,
// not a runnable web export. Keep the player inactive until a browser port exists.
export const gameConfig: {url:string|null;title:string;controls:Record<Language,string>|null} = {
 url:null,
 title:'Codeflow Tower',
 controls:{nl:'WASD / pijltjes: bewegen · Shift: rennen · E: interactie · 1–4: kiezen · J: portfolio · K: skills · Esc: pauze · M: geluid',en:'WASD / arrows: move · Shift: run · E: interact · 1–4: choose · J: portfolio · K: skills · Esc: pause · M: sound'},
};
const screenshots=[{id:'studio',src:'/games/codeflow-tower/studio.webp',nl:'Studio',en:'Studio',altNl:'Screenshot van Codeflow Tower: de speler verkent de studiovloer en krijgt een opdracht van Noor.',altEn:'Codeflow Tower screenshot: the player explores the studio floor and receives a task from Noor.'},{id:'review',src:'/games/codeflow-tower/review.webp',nl:'Managerreview',en:'Manager review',altNl:'Screenshot van Codeflow Tower: een beurtgebaseerde managerreview met skills en scores.',altEn:'Codeflow Tower screenshot: a turn-based manager review with skills and scores.'}];
export default function GameShowcase({lang}:{lang:Language}){
 const en=lang==='en';const [playing,setPlaying]=useState(false);const [session,setSession]=useState(0);const [error,setError]=useState('');const frame=useRef<HTMLIFrameElement>(null);
 async function fullscreen(){try{if(frame.current?.requestFullscreen)await frame.current.requestFullscreen();else setError(en?'Fullscreen is not available in this browser.':'Volledig scherm is niet beschikbaar in deze browser.');}catch{setError(en?'Fullscreen could not be opened. You can keep playing here.':'Volledig scherm kon niet worden geopend. Je kunt hier verder spelen.');}}
 return <section className="game-section container" id="game"><div className="section-heading"><div><p className="eyebrow">04 / {en?'SOFTWARE IN ACTION':'SOFTWARE IN ACTIE'}</p><h2>Codeflow Tower.<br/><span>{en?'From idea to game.':'Van idee naar game.'}</span></h2></div><p className="section-intro">{en?'Your first day at Codeflow Studios. Explore three office floors, help your colleagues and win turn-based manager reviews through creative work.':'Je eerste dag bij Codeflow Studios. Verken drie kantoorverdiepingen, help je collega’s en overtuig managers in beurtgebaseerde reviews met creatief werk.'}</p></div>
 <div className="tower-facts"><span>Godot + C#</span><span>{en?'Single-player RPG':'Singleplayer-RPG'}</span><span>{en?'3 floors · 6 colleague tasks':'3 verdiepingen · 6 collega-opdrachten'}</span><span>Prototype 0.2</span></div>
 <div className="game-player"><div className="game-toolbar"><span><Gamepad2 size={20}/> Codeflow Tower</span><span className="game-engine">{gameConfig.url?'WEB':'WINDOWS · C#'}</span></div>{playing&&gameConfig.url?<><iframe key={session} ref={frame} className="game-frame" src={gameConfig.url} title={gameConfig.title} allow="fullscreen; gamepad; autoplay" allowFullScreen onError={()=>setError(en?'The game could not be loaded. Try restarting it.':'De game kon niet worden geladen. Probeer opnieuw te starten.')}/><div className="game-controls"><button type="button" onClick={fullscreen}><Maximize size={17}/>{en?'Fullscreen':'Volledig scherm'}</button><button type="button" onClick={()=>{setSession(s=>s+1);setError('');}}><RotateCcw size={17}/>{en?'Restart':'Herstart'}</button><button type="button" onClick={()=>{setPlaying(false);setError('');}}><Square size={16}/>{en?'Stop playing':'Stoppen'}</button></div>{gameConfig.controls&&<p className="game-instructions">{gameConfig.controls[lang]}</p>}</>:<><Tabs defaultValue="studio" className="tower-gallery"><TabsList aria-label={en?'Game screenshots':'Gamescreenshots'} className="tower-gallery-tabs">{screenshots.map(s=><TabsTrigger key={s.id} value={s.id}>{en?s.en:s.nl}</TabsTrigger>)}</TabsList>{screenshots.map(s=><TabsContent key={s.id} value={s.id}><figure><img src={s.src} alt={en?s.altEn:s.altNl} width="3840" height="2160" loading="lazy"/><figcaption>{en?'Screenshot from the Windows game':'Screenshot uit de Windowsgame'} · {en?s.en:s.nl}</figcaption></figure></TabsContent>)}</Tabs><div className="tower-availability"><div><h3>{gameConfig.url?(en?'Ready to play?':'Klaar om te spelen?'):(en?'Built for Windows.':'Ontwikkeld voor Windows.')}</h3><p>{gameConfig.url?(en?'Start Codeflow Tower when you are ready.':'Start Codeflow Tower wanneer je er klaar voor bent.'):(en?'This is a preview of our Godot game. A playable browser version is not available yet.':'Dit is een voorproefje van onze Godot-game. Een speelbare browserversie is nog niet beschikbaar.')}</p></div>{gameConfig.url&&<button type="button" className="button" onClick={()=>setPlaying(true)}><Play size={18}/>{en?'Play game':'Speel de game'}</button>}</div></>}{error&&<p className="game-error" role="alert">{error}</p>}</div>
 <div className="tower-craft"><p>{en?'Game logic & progression':'Spellogica & voortgang'}</p><p>{en?'Interactive 2D world':'Interactieve 2D-wereld'}</p><p>{en?'Original pixel art & chiptune':'Eigen pixelart & chiptune'}</p></div></section>;
}
