'use client';
import { ArrowUpRight, Radio, Palette, Code2, Layers3 } from 'lucide-react';
import { Header, Footer, CTA, useLanguage, email } from './shared';
import type { Language } from './shared';

export default function Home({initialLang='nl'}:{initialLang?:Language}){
 const {lang,setLang,en}=useLanguage(initialLang);
 const services=en?[
  {key:'marketing',number:'01',title:'Marketing',kicker:'Real-time relevance',description:'Trend-driven strategy and automated marketing built around your company, audience and market.',href:'/services/marketing',Icon:Radio},
  {key:'design',number:'02',title:'Graphic design',kicker:'A recognisable identity',description:'Logos, visual identities, digital artwork and web design with one consistent visual language.',href:'/services/graphic-design',Icon:Palette},
  {key:'software',number:'03',title:'Software development',kicker:'Ideas made functional',description:'Websites, web applications and custom software — including Codeflow Tower and Skumic Run.',href:'/services/software-development',Icon:Code2},
  {key:'rebranding',number:'04',title:'Rebranding',kicker:'The complete package',description:'Marketing, graphic design and software development combined into one coordinated relaunch.',href:'/services/rebranding',Icon:Layers3}
 ]:[
  {key:'marketing',number:'01',title:'Marketing',kicker:'Realtime relevantie',description:'Strategie op basis van trends en geautomatiseerde marketing, afgestemd op jouw bedrijf, publiek en markt.',href:'/services/marketing',Icon:Radio},
  {key:'design',number:'02',title:'Grafisch design',kicker:'Een herkenbare identiteit',description:'Logo’s, visuele identiteiten, digitaal artwork en webdesign binnen één consequente beeldtaal.',href:'/services/graphic-design',Icon:Palette},
  {key:'software',number:'03',title:'Softwareontwikkeling',kicker:'Ideeën die werken',description:'Websites, webapplicaties en software op maat — inclusief Codeflow Tower en Skumic Run.',href:'/services/software-development',Icon:Code2},
  {key:'rebranding',number:'04',title:'Rebranding',kicker:'Het totaalpakket',description:'Marketing, grafisch design en softwareontwikkeling gecombineerd in één afgestemde herlancering.',href:'/services/rebranding',Icon:Layers3}
 ];
 return <div id="top"><a className="skip" href="#main">{en?'Skip to content':'Naar de inhoud'}</a><Header lang={lang} setLang={setLang}/><main id="main">
 <section className="hero container"><div className="hero-copy"><p className="eyebrow"><span className="accent-line"/> CREATIVE MINDS. TECHNICAL DNA.</p><h1>{en?<>One studio.<br/>Four ways to<br/><em>move forward.</em></>:<>Eén studio.<br/>Vier manieren<br/><em>vooruit.</em></>}</h1><p className="hero-description">{en?'Codeflow Studios connects marketing, design and technology. Choose one discipline, or combine all three through rebranding.':'Codeflow Studios verbindt marketing, design en technologie. Kies één discipline, of combineer ze alle drie via rebranding.'}</p><div className="hero-actions"><CTA href="#services">{en?'Choose a service':'Kies een dienst'}</CTA><a className="text-link" href="#contact">{en?'Contact us':'Contacteer ons'} <ArrowUpRight size={18}/></a></div></div>
 <div className="hero-visual"><div className="visual-label"><span>CODEFLOW / 01</span><span>CREATIVE TECHNOLOGY STUDIO</span></div><img className="flow-art" src="/brand-flow.webp" alt="" width="1536" height="1024"/><div className="signal-caption"><Radio size={19}/><span>{en?'Separate expertise. One creative flow.':'Aparte expertise. Eén creatieve flow.'}</span></div></div><div className="hero-foot"><span>{en?'INDEPENDENT STUDIO · BRUGES, BELGIUM':'ONAFHANKELIJKE STUDIO · BRUGGE, BELGIË'}</span><span>{en?'LOCAL ROOTS. NO BORDERS.':'LOKALE ROOTS. ZONDER GRENZEN.'}</span></div></section>
 <div className="word-strip" aria-hidden="true"><span>MARKETING</span><b>✳</b><span>GRAPHIC DESIGN</span><b>✳</b><span>SOFTWARE DEVELOPMENT</span><b>✳</b><span>REBRANDING</span></div>
 <section className="landing-services container" id="services"><div className="landing-services-heading"><p className="eyebrow">02 / {en?'CHOOSE YOUR ROUTE':'KIES JOUW ROUTE'}</p><h2>{en?<>Each service has<br/><span>its own page and packages.</span></>:<>Elke dienst heeft<br/><span>een eigen pagina en pakketten.</span></>}</h2><p>{en?'The three core disciplines are available separately. Rebranding is the full combination of all three.':'De drie kerndisciplines zijn apart beschikbaar. Rebranding is de volledige combinatie van alle drie.'}</p></div><div className="landing-service-grid">{services.map(({key,number,title,kicker,description,href,Icon})=><a className={`landing-service-card card-${key}`} href={`${href}?lang=${lang}`} key={key}><div className="landing-card-top"><Icon size={29} strokeWidth={1.5}/><span>{number}</span></div><p className="landing-card-kicker">{kicker}</p><h3>{title}</h3><p className="landing-card-description">{description}</p><span className="landing-card-link">{en?'Open service page':'Open dienstpagina'} <ArrowUpRight size={18}/></span></a>)}</div></section>
 <section className="contact-section" id="contact"><div className="container"><div className="contact-top"><p className="eyebrow">03 / {en?'LET’S MAKE SOMETHING MOVE':'LATEN WE IETS IN BEWEGING ZETTEN'}</p><span>BRUGGE ↗ {en?'EVERYWHERE':'OVERAL'}</span></div><h2>{en?<>Got a spark?<br/>Let’s make it <em>flow.</em></>:<>Een idee?<br/>Tijd voor <em>flow.</em></>}</h2><div className="contact-bottom"><a className="contact-email" href={`mailto:${email}`}>{email}<ArrowUpRight size={30}/></a><div className="contact-links"><a href="tel:+32480667519">+32 480 66 75 19</a><a href="https://wa.me/32480667519" target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={15}/></a><a href="https://www.instagram.com/codeflowstudios/" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={15}/></a><a href="https://www.facebook.com/people/Codeflow-Studios/61579077734047/" target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={15}/></a></div></div></div></section>
 </main><Footer lang={lang}/></div>;
}
