'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft,ArrowRight,Check,Download,Sparkles } from 'lucide-react';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { Header,useLanguage,type Language } from './shared';
import { marketingBrandStorageKey } from './marketing-storage';
import { initialBrief, invalidFields, prepareBrandProfile, prepareBrief, planIds,sectors,goals,channels,tones,risks,budgets,languages,customers, type Brief } from './brief';
const names={
 en:{name:'Company name',website:'Website (optional, https://…)',sector:'Industry',offer:'What do you offer, and what makes it different?',customer:'Who do you sell to?',audience:'Describe your ideal customer',markets:'Locations and markets',languages:'Content languages',goal:'Your primary marketing goal',channels:'Channels to focus on',budget:'Monthly marketing budget, excluding subscription',tone:'Your brand voice',risk:'How should your brand approach trends?',avoid:'Topics, claims or trends to avoid (optional)',competitors:'Competitors or brands you admire (optional)'},
 nl:{name:'Bedrijfsnaam',website:'Website (optioneel, https://…)',sector:'Sector',offer:'Wat bied je aan en wat maakt het anders?',customer:'Aan wie verkoop je?',audience:'Beschrijf jouw ideale klant',markets:'Regio’s en markten',languages:'Talen voor je content',goal:'Jouw belangrijkste marketingdoel',channels:'Kanalen waarop je wilt focussen',budget:'Maandelijks marketingbudget, exclusief abonnement',tone:'De stem van jouw merk',risk:'Hoe wil je merk omgaan met trends?',avoid:'Onderwerpen, claims of trends om te vermijden (optioneel)',competitors:'Concurrenten of merken die je inspireren (optioneel)'}
};
const optionNames:Record<Language,Record<string,string>>={
 en:{services:'Professional & local services',retail:'Retail & e-commerce',hospitality:'Food, hospitality & tourism',technology:'Technology & software',creative:'Creative & culture',health:'Health & wellbeing',finance:'Finance & legal',other:'Another industry',b2b:'Businesses',b2c:'Consumers',both:'Both',awareness:'Build brand awareness',leads:'Generate qualified enquiries',sales:'Increase sales',retention:'Retain existing customers',professional:'Clear & professional',friendly:'Warm & approachable',bold:'Bold & direct',playful:'Playful & surprising',focused:'Stay close to my industry',balanced:'Explore adjacent interests',experimental:'Experiment broadly, if relevant',under500:'Under €500','500to1500':'€500–€1,500','1500to5000':'€1,500–€5,000','5000plus':'Over €5,000',unsure:'Help me decide',nl:'Dutch',en:'English',fr:'French',de:'German'},
 nl:{services:'Professionele & lokale diensten',retail:'Retail & e-commerce',hospitality:'Horeca & toerisme',technology:'Technologie & software',creative:'Creatief & cultuur',health:'Gezondheid & welzijn',finance:'Financieel & juridisch',other:'Een andere sector',b2b:'Bedrijven',b2c:'Consumenten',both:'Beide',awareness:'Mijn merk bekender maken',leads:'Relevante aanvragen ontvangen',sales:'Meer verkopen',retention:'Bestaande klanten behouden',professional:'Helder & professioneel',friendly:'Warm & toegankelijk',bold:'Gedurfd & direct',playful:'Speels & verrassend',focused:'Dicht bij mijn sector blijven',balanced:'Verwante interesses verkennen',experimental:'Breed experimenteren, als het relevant is',under500:'Minder dan €500','500to1500':'€500–€1.500','1500to5000':'€1.500–€5.000','5000plus':'Meer dan €5.000',unsure:'Help me kiezen',nl:'Nederlands',en:'Engels',fr:'Frans',de:'Duits'}
};
export default function Onboarding(){
 const {lang,setLang,en}=useLanguage(); const [plan,setPlan]=useState('flow'); const [step,setStep]=useState(0); const [brief,setBrief]=useState<Brief>(initialBrief); const [errors,setErrors]=useState<(keyof Brief)[]>([]); const [complete,setComplete]=useState(false); const [saving,setSaving]=useState(false); const [submitError,setSubmitError]=useState(''); const title=useRef<HTMLHeadingElement>(null); const alert=useRef<HTMLDivElement>(null); const latest=useRef({brief,plan,step});
 useEffect(()=>{latest.current={brief,plan,step};},[brief,plan,step]);
 useEffect(()=>{const p=new URLSearchParams(location.search).get('plan');if(planIds.includes(p as typeof planIds[number]))setPlan(p!);},[]);
 useEffect(()=>{if(step>0)title.current?.focus();},[step,complete]);
 useEffect(()=>{type Context={registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown};const context=(document as Document & {modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_codeflow_onboarding',description:'Read the current company questionnaire draft and missing fields. Does not submit data, activate a subscription or generate an AI strategy.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(input===null||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');const state=latest.current;return {...state,missingFields:invalidFields(state.brief,4),preview:true};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const t=names[lang], options=optionNames[lang], steps=en?['Your company','Your audience','Your strategy','Your voice','Your brief']:['Jouw bedrijf','Jouw doelgroep','Jouw strategie','Jouw merkstem','Jouw briefing'];
 const headings=en?['First, tell us about your business.','Who should your marketing reach?','What does progress look like?','Make it sound like you.','Here’s the foundation of your strategy.']:['Eerst even kennismaken met je bedrijf.','Wie wil je bereiken met je marketing?','Wat wil je marketing bereiken?','Laat het klinken als jouw merk.','Dit is de basis voor jouw strategie.'];
 const hints=en?['A little context makes a big difference.','Specific audiences lead to more relevant ideas.','Choose one main goal. It gives your strategy direction.','Trends should fit your identity, values and boundaries.','Review your answers before finishing your preview.']:['Een beetje context maakt een groot verschil.','Een concrete doelgroep maakt ideeën relevanter.','Kies één hoofddoel. Dat geeft je strategie richting.','Trends moeten passen bij jouw identiteit, waarden en grenzen.','Controleer je antwoorden voor je de preview afrondt.'];
 const set=(key:keyof Brief,value:string|string[])=>{setBrief(v=>({...v,[key]:value}));setErrors(e=>e.filter(k=>k!==key));};
 const show=(key:keyof Brief,value:string|string[])=>Array.isArray(value)?value.map(v=>options[v]||v).join(', '):(['sector','customer','goal','budget','tone','risk'].includes(key)?options[value]:undefined)||value||(en?'Not specified':'Niet ingevuld');
 async function next(e:FormEvent){e.preventDefault();const invalid=invalidFields(brief,step);if(invalid.length){setErrors(invalid);requestAnimationFrame(()=>alert.current?.focus());return;}setErrors([]);setSubmitError('');if(step!==4){setStep(s=>s+1);return;}setSaving(true);try{const response=await fetch('/api/marketing/brand',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(prepareBrandProfile(brief))});if(!response.ok)throw new Error('save failed');const brand=await response.json() as {id:string};localStorage.setItem(marketingBrandStorageKey(location.hostname),brand.id);location.assign(`/dashboard?lang=${lang}`);}catch{setSubmitError(en?'We could not save your profile. Please try again.':'We konden je profiel niet opslaan. Probeer het opnieuw.');requestAnimationFrame(()=>alert.current?.focus());}finally{setSaving(false);}}
 function download(){const value=prepareBrief(brief,plan);const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='codeflow-marketing-brief.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function field(key:keyof Brief,area=false){const id=`field-${key}`;return <div className={`field ${errors.includes(key)?'invalid':''}`} key={key}><label htmlFor={id}>{t[key]}</label>{area?<textarea id={id} value={brief[key] as string} maxLength={key==='competitors'?800:1600} onChange={e=>set(key,e.target.value)} rows={4} aria-invalid={errors.includes(key)}/>:<input id={id} value={brief[key] as string} onChange={e=>set(key,e.target.value)} maxLength={key==='name'?120:300} aria-invalid={errors.includes(key)} placeholder={key==='website'?'https://':undefined}/>}</div>}
 function choice(key:keyof Brief,values:readonly string[],kind:'radio'|'check'|'select'='radio'){const id=`field-${key}`;return <fieldset className={`field ${errors.includes(key)?'invalid':''}`} key={key}><legend id={`${id}-label`}>{t[key]}</legend>{kind==='select'?<Select value={brief[key] as string} onValueChange={v=>set(key,v)}><SelectTrigger className="form-select" aria-labelledby={`${id}-label`} aria-invalid={errors.includes(key)}><SelectValue placeholder={en?'Choose an option':'Kies een optie'}/></SelectTrigger><SelectContent>{values.map(v=><SelectItem value={v} key={v}>{options[v]||v}</SelectItem>)}</SelectContent></Select>:kind==='check'?<div className="choice-grid">{values.map(v=><label className="choice" key={v}><Checkbox checked={(brief[key] as string[]).includes(v)} onCheckedChange={checked=>set(key,checked?[...brief[key] as string[],v]:(brief[key] as string[]).filter(x=>x!==v))}/><span>{options[v]||v}</span></label>)}</div>:<RadioGroup value={brief[key] as string} onValueChange={v=>set(key,v)} className="choice-grid" aria-labelledby={`${id}-label`} aria-invalid={errors.includes(key)}>{values.map(v=><label className="choice" key={v}><RadioGroupItem value={v}/><span>{options[v]||v}</span></label>)}</RadioGroup>}</fieldset>}
 return <div id="top" className="onboarding-page"><a href="#intake" className="skip">{en?'Skip to questionnaire':'Naar de vragenlijst'}</a><Header lang={lang} setLang={setLang} onboarding/><div className="preview-banner">{en?'CODEFLOW MARKETING AI — Build your brand profile. No subscription or payment starts here.':'CODEFLOW MARKETING AI — Maak je merkprofiel. Hier start geen abonnement of betaling.'}</div><main className="intake-layout container" id="intake"><aside className="intake-sidebar"><p className="eyebrow">LET’S FIND YOUR FLOW</p><h1>{en?<>Your business.<br/>Your blueprint.</>:<>Jouw bedrijf.<br/>Jouw blauwdruk.</>}</h1><div className="selected-plan"><span>{en?'Exploring':'Je verkent'}</span><Select value={plan} onValueChange={setPlan}><SelectTrigger aria-label={en?'Selected package':'Gekozen pakket'}><SelectValue/></SelectTrigger><SelectContent>{planIds.map(p=><SelectItem value={p} key={p}>{p[0].toUpperCase()+p.slice(1)}</SelectItem>)}</SelectContent></Select></div><ol className="step-list">{steps.map((s,i)=><li key={s} className={i===step?'current':i<step?'done':''}><button type="button" disabled={i>step} onClick={()=>{setStep(i);setComplete(false);setErrors([]);setSubmitError('');}} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={15}/>:i+1}</span>{s}</button></li>)}</ol><div className="privacy-note"><Sparkles size={20}/><p>{en?'Your answers are sent securely when you create the profile. No content is published automatically.':'Je antwoorden worden veilig verstuurd wanneer je het profiel aanmaakt. Er wordt niets automatisch gepubliceerd.'}</p></div></aside><section className="intake-main"><div className="intake-progress"><span>{complete?(en?'Profile created':'Profiel aangemaakt'):`${en?'Step':'Stap'} ${step+1} / 5`}</span><span>{steps[step]}</span></div><Progress value={complete?100:step*25} aria-label={en?'Questionnaire progress':'Voortgang vragenlijst'}/><div className="intake-heading"><h2 ref={title} tabIndex={-1}>{complete?(en?'Your brand profile is ready.':'Je merkprofiel is klaar.'):headings[step]}</h2><p>{complete?(en?'Codeflow Marketing AI can now match relevant trends to your business. Nothing has been published and no subscription has started.':'Codeflow Marketing AI kan nu relevante trends aan je bedrijf koppelen. Er is niets gepubliceerd en er is geen abonnement gestart.'):hints[step]}</p></div><form onSubmit={next} noValidate>{(errors.length>0||submitError)&&<div className="form-error" role="alert" tabIndex={-1} ref={alert}>{submitError||<>{en?'Check these fields:':'Controleer deze velden:'} {errors.map(k=>t[k]).join(' · ')}</>}</div>}
 {step===0&&<>{field('name')}{field('website')}{choice('sector',sectors,'select')}{field('offer',true)}</>}
 {step===1&&<>{choice('customer',customers)}{field('audience',true)}{field('markets')}{choice('languages',languages,'check')}</>}
 {step===2&&<>{choice('goal',goals)}{choice('channels',channels,'check')}{choice('budget',budgets,'select')}</>}
 {step===3&&<>{choice('tone',tones)}{choice('risk',risks)}{field('avoid',true)}{field('competitors',true)}</>}
 {step===4&&<div className="review"><div className="review-plan"><span>{en?'Concept package':'Conceptpakket'}</span><strong>{plan[0].toUpperCase()+plan.slice(1)}</strong></div>{[[ 'name','website','sector','offer'],['customer','audience','markets','languages'],['goal','channels','budget'],['tone','risk','avoid','competitors']].map((keys,i)=><section key={i}><div className="review-heading"><h3>{steps[i]}</h3><button type="button" onClick={()=>{setStep(i);setComplete(false);}}>{en?'Edit':'Aanpassen'}</button></div><dl>{keys.map(k=><div key={k}><dt>{t[k as keyof Brief]}</dt><dd>{show(k as keyof Brief,brief[k as keyof Brief])}</dd></div>)}</dl></section>)}</div>}
 <div className="form-actions">{step>0&&!complete?<button className="back-button" type="button" disabled={saving} onClick={()=>{setStep(s=>s-1);setErrors([]);setSubmitError('');}}><ArrowLeft size={18}/>{en?'Back':'Terug'}</button>:<span/>}{complete?<button type="button" className="button" onClick={download}><Download size={18}/>{en?'Download your brief':'Download je briefing'}</button>:<button className="button" type="submit" disabled={saving}>{saving?(en?'Creating profile…':'Profiel aanmaken…'):step===4?(en?'Create brand profile':'Merkprofiel aanmaken'):(en?'Continue':'Verder')}<ArrowRight size={18}/></button>}</div></form></section></main></div>;
}
